import { chromium } from '@playwright/test';
import { readFile, writeFile, stat } from 'node:fs/promises';

const asset = new URL('../public/brand/mascot/', import.meta.url);
const columns = 8;
const rows = 6;
const duration = 4000;
const source = await readFile(new URL('reading-frames-v3.png', asset));
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage();
  const result = await page.evaluate(async ({ source, columns, rows, duration }) => {
    const image = new Image();
    image.src = `data:image/png;base64,${source}`;
    await image.decode();
    if (image.width % columns || image.height % rows) throw new Error('Atlas must have equal cells');
    const cellWidth = image.width / columns;
    const cellHeight = image.height / rows;
    const atlas = document.createElement('canvas');
    atlas.width = image.width;
    atlas.height = image.height;
    const original = document.createElement('canvas');
    original.width = image.width;
    original.height = image.height;
    original.getContext('2d').drawImage(image, 0, 0);
    const atlasContext = atlas.getContext('2d');
    // Register the drawings on a common ground line. The generated sheet has
    // drifting cell margins; copying pixels with a fixed anchor removes that
    // unintended sliding without warping or redrawing any body parts.
    for (let frame = 0; frame < columns * rows; frame++) {
      const x = (frame % columns) * cellWidth;
      const y = Math.floor(frame / columns) * cellHeight;
      const pixels = original.getContext('2d').getImageData(x, y, cellWidth, cellHeight).data;
      let left = cellWidth, right = 0, bottom = 0;
      for (let row = 0; row < cellHeight; row++) {
        for (let col = 0; col < cellWidth; col++) {
          if (pixels[(row * cellWidth + col) * 4 + 3] > 32) {
            left = Math.min(left, col);
            right = Math.max(right, col);
            bottom = Math.max(bottom, row);
          }
        }
      }
      const offsetX = Math.round((cellWidth - 1 - left - right) / 2);
      const offsetY = cellHeight - 8 - bottom;
      atlasContext.save();
      atlasContext.beginPath();
      atlasContext.rect(x, y, cellWidth, cellHeight);
      atlasContext.clip();
      atlasContext.drawImage(image, x, y, cellWidth, cellHeight,
        x + offsetX, y + offsetY, cellWidth, cellHeight);
      atlasContext.restore();
    }
    const webp = atlas.toDataURL('image/webp', 0.92).split(',')[1];
    const canvas = document.createElement('canvas');
    canvas.width = cellWidth * 2;
    canvas.height = cellHeight * 2;
    const ctx = canvas.getContext('2d');
    const draw = (frame) => {
      ctx.fillStyle = '#f8f0e4';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(atlas, (frame % columns) * cellWidth, Math.floor(frame / columns) * cellHeight,
        cellWidth, cellHeight, 0, 0, canvas.width, canvas.height);
    };
    draw(0);
    const stream = canvas.captureStream(24);
    const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp9', videoBitsPerSecond: 1500000 });
    const chunks = [];
    recorder.ondataavailable = e => { if (e.data.size) chunks.push(e.data); };
    const recorded = new Promise(resolve => { recorder.onstop = resolve; });
    recorder.start();
    const start = performance.now();
    await new Promise(resolve => {
      function tick(now) {
        const elapsed = now - start;
        draw(Math.min(columns * rows - 1, Math.floor(elapsed / duration * columns * rows)));
        if (elapsed < duration) requestAnimationFrame(tick);
        else { draw(0); resolve(); }
      }
      requestAnimationFrame(tick);
    });
    recorder.stop();
    await recorded;
    stream.getTracks().forEach(track => track.stop());
    const video = await new Promise(resolve => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result).split(',')[1]);
      reader.readAsDataURL(new Blob(chunks, { type: 'video/webm' }));
    });
    return { webp, video, cellWidth, cellHeight };
  }, { source: source.toString('base64'), columns, rows, duration });
  await writeFile(new URL('reading-frames-v3.webp', asset), Buffer.from(result.webp, 'base64'));
  await writeFile(new URL('reading-loop-v3.webm', asset), Buffer.from(result.video, 'base64'));
  const keyframes = Array.from({ length: columns * rows }, (_, index) =>
    `  ${(index / (columns * rows) * 100).toFixed(6)}% { background-position: ${(index % columns) / (columns - 1) * 100}% ${Math.floor(index / columns) / (rows - 1) * 100}%; }`,
  ).join('\n');
  await writeFile(new URL('../src/components/BooksydeMascot.frames.css', import.meta.url),
    `/* Generated by scripts/export-mascot.mjs: 48 complete drawings, no whole-image transforms. */\n@keyframes booksyde-mascot-reading {\n${keyframes}\n  100% { background-position: 0% 0%; }\n}\n`);
  console.log(JSON.stringify({ frames: columns * rows, durationMs: duration, cell: [result.cellWidth, result.cellHeight], atlasBytes: (await stat(new URL('reading-frames-v3.webp', asset))).size }));
} finally { await browser.close(); }
