import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { MessageSquare, Pencil, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
type CommentRow={id:string;body:string;created_at:string;user_id:string;volume_id:string|null;profiles:{display_name:string}|null};
export function CommentSection({mangaId,volumeId,title="Comentários"}:{mangaId:string;volumeId?:string|null;title?:string}){
 const {user}=useAuth();const qc=useQueryClient();const [body,setBody]=useState("");const [editing,setEditing]=useState<string|null>(null);const [editBody,setEditBody]=useState("");const scope=volumeId??"manga";const queryKey=["comments",mangaId,scope];
 const {data:comments=[]}=useQuery({queryKey,queryFn:async()=>{let q=supabase.from("comments").select("id,body,created_at,user_id,volume_id,profiles(display_name)").eq("manga_id",mangaId).order("created_at",{ascending:false});q=volumeId?q.eq("volume_id",volumeId):q.is("volume_id",null);const {data,error}=await q;if(error)throw error;return(data??[]) as unknown as CommentRow[]}});
 const add=useMutation({mutationFn:async()=>{const {error}=await supabase.from("comments").insert({manga_id:mangaId,volume_id:volumeId??null,user_id:user!.id,body:body.trim()});if(error)throw error},onSuccess:()=>{setBody("");qc.invalidateQueries({queryKey});toast.success("Comentário publicado")},onError:(e:Error)=>toast.error(e.message)});
 const update=useMutation({mutationFn:async()=>{const {error}=await supabase.from("comments").update({body:editBody.trim()}).eq("id",editing!).eq("user_id",user!.id);if(error)throw error},onSuccess:()=>{setEditing(null);setEditBody("");qc.invalidateQueries({queryKey});toast.success("Comentário atualizado")},onError:(e:Error)=>toast.error(e.message)});
 const remove=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("comments").delete().eq("id",id).eq("user_id",user!.id);if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey}),onError:(e:Error)=>toast.error(e.message)});
 return <section className="rounded-[1.6rem] border border-border/70 bg-card/70 p-5 sm:p-6"><div className="flex items-center gap-2"><MessageSquare className="size-5 text-primary"/><h3 className="font-display text-xl">{title}</h3><span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs text-primary">{comments.length}</span></div><p className="mt-1 text-sm text-muted-foreground">Compartilhe sua opinião sem spoilers.</p>
 {user?<div className="mt-5 space-y-2"><Textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Escreva um comentário..." rows={3}/><div className="flex justify-end"><Button size="sm" disabled={!body.trim()||add.isPending} onClick={()=>add.mutate()}>Publicar comentário</Button></div></div>:<p className="mt-5 text-sm text-muted-foreground"><Link to="/auth" className="font-medium text-primary underline">Entre na sua conta</Link> para comentar.</p>}
 <ul className="mt-6 space-y-3">{comments.map(c=><li key={c.id} className="rounded-xl border border-border/60 bg-background/35 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{c.profiles?.display_name??"Leitor"}</p><time className="text-[11px] text-muted-foreground">{new Date(c.created_at).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</time></div>{user?.id===c.user_id?<div className="flex gap-1"><button className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground" onClick={()=>{setEditing(c.id);setEditBody(c.body)}} aria-label="Editar"><Pencil className="size-3.5"/></button><button className="rounded-md p-1.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" onClick={()=>remove.mutate(c.id)} aria-label="Excluir"><Trash2 className="size-3.5"/></button></div>:null}</div>{editing===c.id?<div className="mt-3 space-y-2"><Textarea value={editBody} onChange={e=>setEditBody(e.target.value)} rows={3}/><div className="flex gap-2"><Button size="sm" disabled={!editBody.trim()||update.isPending} onClick={()=>update.mutate()}>Salvar</Button><Button size="sm" variant="ghost" onClick={()=>setEditing(null)}><X className="size-4"/>Cancelar</Button></div></div>:<p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{c.body}</p>}</li>)}{!comments.length?<li className="rounded-xl border border-dashed border-border/70 p-6 text-center text-sm text-muted-foreground">Nenhum comentário ainda. Comece a conversa.</li>:null}</ul></section>
}
