import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, FileText, Plus, Search, Upload } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";

const db = supabase as any;
type Contract = { id:string; publisher_id:string; title:string; status:string; publisher_percentage:number; booksyde_percentage:number; contract_date:string; starts_at:string; ends_at:string|null; file_path:string; file_name:string; notes:string|null; created_at:string };
type Profile = { id:string; display_name:string; avatar_url:string|null };
const brDate=(v?:string|null)=>v?new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR"):"Sem prazo";
const statusLabel=(s:string)=>({active:"Vigente",draft:"Rascunho",expired:"Expirado",cancelled:"Cancelado"}[s]??s);

async function signedContractUrl(path:string){ const {data,error}=await db.storage.from("contracts").createSignedUrl(path,300); if(error) throw error; return data.signedUrl as string; }
function ContractDetails({contract, profile}:{contract:Contract;profile?:Profile}){
 const openFile=async(download=false)=>{try{const url=await signedContractUrl(contract.file_path); if(download){const a=document.createElement("a");a.href=url;a.download=contract.file_name;a.target="_blank";a.click();}else window.open(url,"_blank","noopener,noreferrer");}catch(e:any){toast.error(e?.message??"Não foi possível abrir o contrato.");}};
 return <div className="space-y-5"><div className="flex items-center gap-3"><Avatar className="size-12"><AvatarImage src={profile?.avatar_url??undefined}/><AvatarFallback>{(profile?.display_name??"E").slice(0,2).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate font-semibold">{profile?.display_name??"Sua editora"}</p><div className="mt-1"><Badge variant={contract.status==="active"?"default":"outline"}>{statusLabel(contract.status)}</Badge></div></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Participação da editora",`${contract.publisher_percentage}%`],["BookSyde",`${contract.booksyde_percentage}%`],["Contratação",brDate(contract.contract_date)],["Vigência",`${brDate(contract.starts_at)} — ${brDate(contract.ends_at)}`]].map(([k,v])=><div key={k} className="rounded-xl border bg-muted/15 p-4"><p className="text-xs text-muted-foreground">{k}</p><p className="mt-1 font-semibold">{v}</p></div>)}</div>{contract.notes?<div className="rounded-xl border p-4"><p className="text-xs font-medium text-muted-foreground">Observações</p><p className="mt-2 whitespace-pre-wrap text-sm">{contract.notes}</p></div>:null}<div className="flex flex-wrap items-center gap-3 rounded-xl border p-4"><FileText className="size-8 text-primary"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{contract.file_name}</p><p className="text-xs text-muted-foreground">Arquivo contratual privado</p></div><Button variant="outline" onClick={()=>void openFile(false)}><Eye className="size-4"/> Visualizar</Button><Button onClick={()=>void openFile(true)}><Download className="size-4"/> Baixar</Button></div></div>;
}

export function PublisherContractPanel({publisherId}:{publisherId:string}){
 const q=useQuery({queryKey:["publisher-contract",publisherId],queryFn:async()=>{const {data,error}=await db.from("publisher_contracts").select("*").eq("publisher_id",publisherId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data as Contract|null;}});
 if(q.isLoading)return <p className="p-6 text-sm text-muted-foreground">Carregando contrato…</p>;
 if(q.isError)return <div className="rounded-2xl border border-destructive/30 p-5 text-sm">Não foi possível consultar o contrato. Execute o arquivo <b>BOOKSYDE_CONTRATOS.sql</b> no Supabase.</div>;
 if(!q.data)return <div className="rounded-2xl border border-dashed p-8 text-center"><FileText className="mx-auto size-9 text-muted-foreground"/><h2 className="mt-3 font-semibold">Nenhum contrato cadastrado</h2><p className="mt-1 text-sm text-muted-foreground">Quando o administrador cadastrar o contrato da editora, ele aparecerá aqui.</p></div>;
 return <div className="rounded-2xl border bg-card/60 p-5"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Contrato ativo</p><h2 className="mt-1 font-display text-2xl">{q.data.title}</h2></div><ContractDetails contract={q.data}/></div>;
}

export function AdminContractsPanel(){
 const qc=useQueryClient(); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<Contract|null>(null); const [creating,setCreating]=useState(false);
 const contracts=useQuery({queryKey:["admin-contracts"],queryFn:async()=>{const {data,error}=await db.from("publisher_contracts").select("*").order("created_at",{ascending:false});if(error)throw error;return (data??[]) as Contract[];}});
 const profiles=useQuery({queryKey:["admin-contract-profiles",(contracts.data??[]).map(x=>x.publisher_id).join(",")],enabled:!!contracts.data?.length,queryFn:async()=>{const ids=[...new Set((contracts.data??[]).map(x=>x.publisher_id))];const {data,error}=await db.from("profiles").select("id,display_name,avatar_url").in("id",ids);if(error)throw error;return (data??[]) as Profile[];}});
 const profileMap=useMemo(()=>new Map((profiles.data??[]).map(p=>[p.id,p])),[profiles.data]); const filtered=(contracts.data??[]).filter(c=>(profileMap.get(c.publisher_id)?.display_name??"").toLowerCase().includes(search.toLowerCase()));
 return <><div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="font-display text-3xl">Contratos</h1><p className="text-sm text-muted-foreground">Gerencie os contratos das editoras parceiras.</p></div><Button onClick={()=>setCreating(true)}><Plus className="size-4"/> Novo contrato</Button></div><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar editora..." className="pl-9"/></div>{contracts.isError?<div className="rounded-xl border border-destructive/30 p-4 text-sm">Não foi possível carregar os contratos. Execute <b>BOOKSYDE_CONTRATOS.sql</b>.</div>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(c=>{const p=profileMap.get(c.publisher_id);return <article key={c.id} className="rounded-2xl border bg-card/65 p-5"><div className="flex flex-col items-center text-center"><Avatar className="size-20"><AvatarImage src={p?.avatar_url??undefined}/><AvatarFallback className="text-xl">{(p?.display_name??"E").slice(0,2).toUpperCase()}</AvatarFallback></Avatar><h2 className="mt-3 line-clamp-1 font-semibold">{p?.display_name??"Editora"}</h2><Badge className="mt-2" variant={c.status==="active"?"default":"outline"}>{statusLabel(c.status)}</Badge><Button className="mt-5 w-full" variant="outline" onClick={()=>setSelected(c)}><Eye className="size-4"/> Visualizar</Button></div></article>})}{contracts.isSuccess&&!filtered.length?<div className="col-span-full rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhum contrato encontrado.</div>:null}</div>}</div><Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{selected?.title??"Contrato"}</DialogTitle></DialogHeader>{selected?<ContractDetails contract={selected} profile={profileMap.get(selected.publisher_id)}/>:null}</DialogContent></Dialog><CreateContractDialog open={creating} onOpenChange={setCreating} onSaved={()=>void qc.invalidateQueries({queryKey:["admin-contracts"]})}/></>;
}

function CreateContractDialog({open,onOpenChange,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;onSaved:()=>void}){
 const [publisherId,setPublisherId]=useState(""); const [percentage,setPercentage]=useState("70"); const [contractDate,setContractDate]=useState(""); const [startsAt,setStartsAt]=useState(""); const [endsAt,setEndsAt]=useState(""); const [notes,setNotes]=useState(""); const [file,setFile]=useState<File|null>(null);
 const publishers=useQuery({queryKey:["contract-publishers"],enabled:open,queryFn:async()=>{const {data:roles,error}=await db.from("user_roles").select("user_id").eq("role","editora");if(error)throw error;const ids=[...new Set((roles??[]).map((r:any)=>r.user_id))];if(!ids.length)return [] as Profile[];const {data,error:e}=await db.from("profiles").select("id,display_name,avatar_url").in("id",ids);if(e)throw e;return (data??[]) as Profile[];}});
 const save=useMutation({mutationFn:async()=>{if(!publisherId||!file||!contractDate||!startsAt)throw new Error("Preencha editora, arquivo e datas obrigatórias.");const pct=Number(percentage);if(!Number.isFinite(pct)||pct<0||pct>100)throw new Error("A porcentagem deve estar entre 0 e 100.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${publisherId}/${crypto.randomUUID()}-${safe}`;const {error:up}=await db.storage.from("contracts").upload(path,file,{contentType:file.type||"application/pdf",upsert:false});if(up)throw up;const {error}=await db.from("publisher_contracts").insert({publisher_id:publisherId,title:"Contrato editorial BookSyde",status:"active",publisher_percentage:pct,booksyde_percentage:100-pct,contract_date:contractDate,starts_at:startsAt,ends_at:endsAt||null,file_path:path,file_name:file.name,notes:notes||null});if(error){await db.storage.from("contracts").remove([path]);throw error;}},onSuccess:()=>{toast.success("Contrato cadastrado.");onOpenChange(false);onSaved();setFile(null);setPublisherId("");},onError:(e:any)=>toast.error(e?.message??"Não foi possível cadastrar o contrato.")});
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Novo contrato</DialogTitle></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate();}}><div className="sm:col-span-2"><Label>Editora</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={publisherId} onChange={e=>setPublisherId(e.target.value)} required><option value="">Selecione...</option>{(publishers.data??[]).map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></div><div><Label>Participação da editora (%)</Label><Input type="number" min="0" max="100" step="0.01" value={percentage} onChange={e=>setPercentage(e.target.value)} required/></div><div><Label>BookSyde (%)</Label><Input value={String(100-(Number(percentage)||0))} disabled/></div><div><Label>Data da contratação</Label><Input type="date" value={contractDate} onChange={e=>setContractDate(e.target.value)} required/></div><div><Label>Início da vigência</Label><Input type="date" value={startsAt} onChange={e=>setStartsAt(e.target.value)} required/></div><div><Label>Fim da vigência</Label><Input type="date" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></div><div><Label>Contrato (PDF)</Label><Input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)} required/></div><div className="sm:col-span-2"><Label>Observações</Label><textarea className="mt-1 min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={notes} onChange={e=>setNotes(e.target.value)}/></div><Button className="sm:col-span-2" disabled={save.isPending} type="submit"><Upload className="size-4"/>{save.isPending?"Enviando...":"Cadastrar contrato"}</Button></form></DialogContent></Dialog>;
}
