import { createHmac, timingSafeEqual } from "node:crypto";

function env(name: string) { return (process.env[name] ?? "").trim(); }
function secret() { const v=env("BOOKSYDE_DRIVE_PROXY_SECRET"); if(!v) throw new Error("BOOKSYDE_DRIVE_PROXY_SECRET não configurado."); return v; }
function signature(volumeId:string,fileId:string,expires:number){return createHmac("sha256",secret()).update(`${volumeId}:${fileId}:${expires}`).digest("hex");}
export function createDriveProxyUrl(volumeId:string,fileId:string,ttlSeconds=3600){const expires=Math.floor(Date.now()/1000)+ttlSeconds;return `/api/reader-pages?volumeId=${encodeURIComponent(volumeId)}&fileId=${encodeURIComponent(fileId)}&expires=${expires}&sig=${signature(volumeId,fileId,expires)}`;}
export function validateDriveProxy(volumeId:string,fileId:string,expires:number,sig:string){if(!volumeId||!fileId||!Number.isFinite(expires)||expires<Math.floor(Date.now()/1000))return false;const expected=signature(volumeId,fileId,expires);if(sig.length!==expected.length)return false;return timingSafeEqual(Buffer.from(sig),Buffer.from(expected));}
export function extractDriveFolderId(value:string){const s=value.trim(); const m=s.match(/\/folders\/([a-zA-Z0-9_-]+)/); return m?.[1] ?? (/^[a-zA-Z0-9_-]{10,}$/.test(s)?s:null);}
export async function listDriveFolder(folderId:string){const key=env("GOOGLE_DRIVE_API_KEY");if(!key) throw new Error("GOOGLE_DRIVE_API_KEY não configurada.");const q=`'${folderId}' in parents and trashed = false`;const fields="files(id,name,mimeType,size)";const u=`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=${encodeURIComponent(fields)}&pageSize=1000&orderBy=name_natural&key=${encodeURIComponent(key)}`;const r=await fetch(u);if(!r.ok) throw new Error(`Google Drive recusou a listagem (${r.status}). Verifique se a pasta está como 'Qualquer pessoa com o link'.`);const j=await r.json() as {files?:Array<{id:string;name:string;mimeType:string;size?:string}>};return j.files??[];}
export async function fetchDriveFile(fileId:string, range?:string|null, signal?:AbortSignal){const key=env("GOOGLE_DRIVE_API_KEY");const url=key?`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?alt=media&key=${encodeURIComponent(key)}`:`https://drive.usercontent.google.com/download?id=${encodeURIComponent(fileId)}&export=download&confirm=t`;const headers=new Headers();if(range)headers.set("Range",range);return fetch(url,{redirect:"follow",headers,signal:signal??null});}

