/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DireitosAutoraisRouteImport } from './routes/direitos-autorais'
import { Route as EditoraRouteImport } from './routes/editora'
import { Route as EstanteFisicaRouteImport } from './routes/estante-fisica'
import { Route as MapaLiterarioRouteImport } from './routes/mapa-literario'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MeuPerfilRouteImport } from './routes/meu-perfil'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as SocialRouteImport } from './routes/social'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TermosVendedorRouteImport } from './routes/termos-vendedor'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as AdminAnunciosRouteImport } from './routes/admin_.anuncios'
import { Route as AdminAssinaturasRouteImport } from './routes/admin_.assinaturas'
import { Route as AdminContratosRouteImport } from './routes/admin_.contratos'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'
import { Route as AdminDenunciasRouteImport } from './routes/admin_.denuncias'
import { Route as AdminDoacoesRouteImport } from './routes/admin_.doacoes'
import { Route as AdminFinanceiroRouteImport } from './routes/admin_.financeiro'
import { Route as AdminMarketplaceRouteImport } from './routes/admin_.marketplace'
import { Route as AdminModeracaoRouteImport } from './routes/admin_.moderacao'
import { Route as AdminPedidosRouteImport } from './routes/admin_.pedidos'
import { Route as AdminReembolsosRouteImport } from './routes/admin_.reembolsos'
import { Route as AdminSuporteRouteImport } from './routes/admin_.suporte'
import { Route as AdminUsuariosRouteImport } from './routes/admin_.usuarios'
import { Route as ApiAdminMangasRouteImport } from './routes/api.admin-mangas'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin-users'
import { Route as ApiDesktopDownloadRouteImport } from './routes/api.desktop-download'
import { Route as ApiDriveFolderSyncRouteImport } from './routes/api.drive-folder-sync'
import { Route as ApiR2DeleteRouteImport } from './routes/api.r2-delete'
import { Route as ApiR2UploadRouteImport } from './routes/api.r2-upload'
import { Route as ApiReaderPagesRouteImport } from './routes/api.reader-pages'
import { Route as EditoraCatalogoRouteImport } from './routes/editora_.catalogo'
import { Route as EditoraConfiguracoesRouteImport } from './routes/editora_.configuracoes'
import { Route as EditoraContratosRouteImport } from './routes/editora_.contratos'
import { Route as EditoraFinanceiroRouteImport } from './routes/editora_.financeiro'
import { Route as EditoraRelatoriosRouteImport } from './routes/editora_.relatorios'
import { Route as LerVolumeIdRouteImport } from './routes/ler.$volumeId'
import { Route as MangaSlugRouteImport } from './routes/manga.$slug'
import { Route as MarketplaceVendedorRouteImport } from './routes/marketplace_.vendedor'
import { Route as PlanosRetornoRouteImport } from './routes/planos.retorno'
import { Route as VendedorFinanceiroRouteImport } from './routes/vendedor_.financeiro'
import { Route as VendedorLojaRouteImport } from './routes/vendedor_.loja'
import { Route as VendedorPedidosRouteImport } from './routes/vendedor_.pedidos'
import { Route as VendedorPublicacoesRouteImport } from './routes/vendedor_.publicacoes'
import { Route as ApiMarketplaceCheckoutRouteImport } from './routes/api/marketplace/checkout'
import { Route as ApiMarketplaceOrderRouteImport } from './routes/api/marketplace/order'
import { Route as ApiMarketplaceSellerOnboardingRouteImport } from './routes/api/marketplace/seller-onboarding'
import { Route as MarketplaceItemListingIdRouteImport } from './routes/marketplace_.item.$listingId'
import { Route as MarketplaceVendedorSellerIdRouteImport } from './routes/marketplace_.vendedor_.$sellerId'
import { Route as ApiPublicMarketplaceWebhookRouteImport } from './routes/api/public/marketplace/webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitosAutoraisRoute = DireitosAutoraisRouteImport.update({
  id: '/direitos-autorais',
  path: '/direitos-autorais',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoraRoute = EditoraRouteImport.update({
  id: '/editora',
  path: '/editora',
  getParentRoute: () => rootRouteImport,
} as any)
const EstanteFisicaRoute = EstanteFisicaRouteImport.update({
  id: '/estante-fisica',
  path: '/estante-fisica',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaLiterarioRoute = MapaLiterarioRouteImport.update({
  id: '/mapa-literario',
  path: '/mapa-literario',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPerfilRoute = MeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosVendedorRoute = TermosVendedorRouteImport.update({
  id: '/termos-vendedor',
  path: '/termos-vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/admin_/anuncios',
  path: '/admin/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/admin_/assinaturas',
  path: '/admin/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosRoute = AdminContratosRouteImport.update({
  id: '/admin_/contratos',
  path: '/admin/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/admin_/denuncias',
  path: '/admin/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoacoesRoute = AdminDoacoesRouteImport.update({
  id: '/admin_/doacoes',
  path: '/admin/doacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin_/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/admin_/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModeracaoRoute = AdminModeracaoRouteImport.update({
  id: '/admin_/moderacao',
  path: '/admin/moderacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin_/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReembolsosRoute = AdminReembolsosRouteImport.update({
  id: '/admin_/reembolsos',
  path: '/admin/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/admin_/suporte',
  path: '/admin/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin_/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMangasRoute = ApiAdminMangasRouteImport.update({
  id: '/api/admin-mangas',
  path: '/api/admin-mangas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin-users',
  path: '/api/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopDownloadRoute = ApiDesktopDownloadRouteImport.update({
  id: '/api/desktop-download',
  path: '/api/desktop-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFolderSyncRoute = ApiDriveFolderSyncRouteImport.update({
  id: '/api/drive-folder-sync',
  path: '/api/drive-folder-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2DeleteRoute = ApiR2DeleteRouteImport.update({
  id: '/api/r2-delete',
  path: '/api/r2-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2UploadRoute = ApiR2UploadRouteImport.update({
  id: '/api/r2-upload',
  path: '/api/r2-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReaderPagesRoute = ApiReaderPagesRouteImport.update({
  id: '/api/reader-pages',
  path: '/api/reader-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoraCatalogoRoute = EditoraCatalogoRouteImport.update({
  id: '/editora_/catalogo',
  path: '/editora/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoraConfiguracoesRoute = EditoraConfiguracoesRouteImport.update({
  id: '/editora_/configuracoes',
  path: '/editora/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoraContratosRoute = EditoraContratosRouteImport.update({
  id: '/editora_/contratos',
  path: '/editora/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoraFinanceiroRoute = EditoraFinanceiroRouteImport.update({
  id: '/editora_/financeiro',
  path: '/editora/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoraRelatoriosRoute = EditoraRelatoriosRouteImport.update({
  id: '/editora_/relatorios',
  path: '/editora/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LerVolumeIdRoute = LerVolumeIdRouteImport.update({
  id: '/ler/$volumeId',
  path: '/ler/$volumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaSlugRoute = MangaSlugRouteImport.update({
  id: '/manga/$slug',
  path: '/manga/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceVendedorRoute = MarketplaceVendedorRouteImport.update({
  id: '/marketplace_/vendedor',
  path: '/marketplace/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRetornoRoute = PlanosRetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => PlanosRoute,
} as any)
const VendedorFinanceiroRoute = VendedorFinanceiroRouteImport.update({
  id: '/vendedor_/financeiro',
  path: '/vendedor/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorLojaRoute = VendedorLojaRouteImport.update({
  id: '/vendedor_/loja',
  path: '/vendedor/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorPedidosRoute = VendedorPedidosRouteImport.update({
  id: '/vendedor_/pedidos',
  path: '/vendedor/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorPublicacoesRoute = VendedorPublicacoesRouteImport.update({
  id: '/vendedor_/publicacoes',
  path: '/vendedor/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceCheckoutRoute = ApiMarketplaceCheckoutRouteImport.update({
  id: '/api/marketplace/checkout',
  path: '/api/marketplace/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceOrderRoute = ApiMarketplaceOrderRouteImport.update({
  id: '/api/marketplace/order',
  path: '/api/marketplace/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceSellerOnboardingRoute =
  ApiMarketplaceSellerOnboardingRouteImport.update({
    id: '/api/marketplace/seller-onboarding',
    path: '/api/marketplace/seller-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceItemListingIdRoute =
  MarketplaceItemListingIdRouteImport.update({
    id: '/marketplace_/item/$listingId',
    path: '/marketplace/item/$listingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceVendedorSellerIdRoute =
  MarketplaceVendedorSellerIdRouteImport.update({
    id: '/marketplace_/vendedor_/$sellerId',
    path: '/marketplace/vendedor/$sellerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketplaceWebhookRoute =
  ApiPublicMarketplaceWebhookRouteImport.update({
    id: '/api/public/marketplace/webhook',
    path: '/api/public/marketplace/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/compras': typeof ComprasRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/direitos-autorais': typeof DireitosAutoraisRoute
  '/editora': typeof EditoraRoute
  '/estante-fisica': typeof EstanteFisicaRoute
  '/mapa-literario': typeof MapaLiterarioRoute
  '/marketplace': typeof MarketplaceRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/planos': typeof PlanosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/social': typeof SocialRoute
  '/studio': typeof StudioRoute
  '/termos': typeof TermosRoute
  '/termos-vendedor': typeof TermosVendedorRoute
  '/vendedor': typeof VendedorRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/doacoes': typeof AdminDoacoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/admin-mangas': typeof ApiAdminMangasRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/desktop-download': typeof ApiDesktopDownloadRoute
  '/api/drive-folder-sync': typeof ApiDriveFolderSyncRoute
  '/api/r2-delete': typeof ApiR2DeleteRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/api/reader-pages': typeof ApiReaderPagesRoute
  '/editora/catalogo': typeof EditoraCatalogoRoute
  '/editora/configuracoes': typeof EditoraConfiguracoesRoute
  '/editora/contratos': typeof EditoraContratosRoute
  '/editora/financeiro': typeof EditoraFinanceiroRoute
  '/editora/relatorios': typeof EditoraRelatoriosRoute
  '/ler/$volumeId': typeof LerVolumeIdRoute
  '/manga/$slug': typeof MangaSlugRoute
  '/marketplace/vendedor': typeof MarketplaceVendedorRoute
  '/planos/retorno': typeof PlanosRetornoRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/loja': typeof VendedorLojaRoute
  '/vendedor/pedidos': typeof VendedorPedidosRoute
  '/vendedor/publicacoes': typeof VendedorPublicacoesRoute
  '/api/marketplace/checkout': typeof ApiMarketplaceCheckoutRoute
  '/api/marketplace/order': typeof ApiMarketplaceOrderRoute
  '/api/marketplace/seller-onboarding': typeof ApiMarketplaceSellerOnboardingRoute
  '/marketplace/item/$listingId': typeof MarketplaceItemListingIdRoute
  '/marketplace/vendedor/$sellerId': typeof MarketplaceVendedorSellerIdRoute
  '/api/public/marketplace/webhook': typeof ApiPublicMarketplaceWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/compras': typeof ComprasRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/direitos-autorais': typeof DireitosAutoraisRoute
  '/editora': typeof EditoraRoute
  '/estante-fisica': typeof EstanteFisicaRoute
  '/mapa-literario': typeof MapaLiterarioRoute
  '/marketplace': typeof MarketplaceRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/planos': typeof PlanosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/social': typeof SocialRoute
  '/studio': typeof StudioRoute
  '/termos': typeof TermosRoute
  '/termos-vendedor': typeof TermosVendedorRoute
  '/vendedor': typeof VendedorRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/doacoes': typeof AdminDoacoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/admin-mangas': typeof ApiAdminMangasRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/desktop-download': typeof ApiDesktopDownloadRoute
  '/api/drive-folder-sync': typeof ApiDriveFolderSyncRoute
  '/api/r2-delete': typeof ApiR2DeleteRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/api/reader-pages': typeof ApiReaderPagesRoute
  '/editora/catalogo': typeof EditoraCatalogoRoute
  '/editora/configuracoes': typeof EditoraConfiguracoesRoute
  '/editora/contratos': typeof EditoraContratosRoute
  '/editora/financeiro': typeof EditoraFinanceiroRoute
  '/editora/relatorios': typeof EditoraRelatoriosRoute
  '/ler/$volumeId': typeof LerVolumeIdRoute
  '/manga/$slug': typeof MangaSlugRoute
  '/marketplace/vendedor': typeof MarketplaceVendedorRoute
  '/planos/retorno': typeof PlanosRetornoRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/loja': typeof VendedorLojaRoute
  '/vendedor/pedidos': typeof VendedorPedidosRoute
  '/vendedor/publicacoes': typeof VendedorPublicacoesRoute
  '/api/marketplace/checkout': typeof ApiMarketplaceCheckoutRoute
  '/api/marketplace/order': typeof ApiMarketplaceOrderRoute
  '/api/marketplace/seller-onboarding': typeof ApiMarketplaceSellerOnboardingRoute
  '/marketplace/item/$listingId': typeof MarketplaceItemListingIdRoute
  '/marketplace/vendedor/$sellerId': typeof MarketplaceVendedorSellerIdRoute
  '/api/public/marketplace/webhook': typeof ApiPublicMarketplaceWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/compras': typeof ComprasRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/direitos-autorais': typeof DireitosAutoraisRoute
  '/editora': typeof EditoraRoute
  '/estante-fisica': typeof EstanteFisicaRoute
  '/mapa-literario': typeof MapaLiterarioRoute
  '/marketplace': typeof MarketplaceRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/planos': typeof PlanosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/social': typeof SocialRoute
  '/studio': typeof StudioRoute
  '/termos': typeof TermosRoute
  '/termos-vendedor': typeof TermosVendedorRoute
  '/vendedor': typeof VendedorRoute
  '/admin_/anuncios': typeof AdminAnunciosRoute
  '/admin_/assinaturas': typeof AdminAssinaturasRoute
  '/admin_/contratos': typeof AdminContratosRoute
  '/admin_/dashboard': typeof AdminDashboardRoute
  '/admin_/denuncias': typeof AdminDenunciasRoute
  '/admin_/doacoes': typeof AdminDoacoesRoute
  '/admin_/financeiro': typeof AdminFinanceiroRoute
  '/admin_/marketplace': typeof AdminMarketplaceRoute
  '/admin_/moderacao': typeof AdminModeracaoRoute
  '/admin_/pedidos': typeof AdminPedidosRoute
  '/admin_/reembolsos': typeof AdminReembolsosRoute
  '/admin_/suporte': typeof AdminSuporteRoute
  '/admin_/usuarios': typeof AdminUsuariosRoute
  '/api/admin-mangas': typeof ApiAdminMangasRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/desktop-download': typeof ApiDesktopDownloadRoute
  '/api/drive-folder-sync': typeof ApiDriveFolderSyncRoute
  '/api/r2-delete': typeof ApiR2DeleteRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/api/reader-pages': typeof ApiReaderPagesRoute
  '/editora_/catalogo': typeof EditoraCatalogoRoute
  '/editora_/configuracoes': typeof EditoraConfiguracoesRoute
  '/editora_/contratos': typeof EditoraContratosRoute
  '/editora_/financeiro': typeof EditoraFinanceiroRoute
  '/editora_/relatorios': typeof EditoraRelatoriosRoute
  '/ler/$volumeId': typeof LerVolumeIdRoute
  '/manga/$slug': typeof MangaSlugRoute
  '/marketplace_/vendedor': typeof MarketplaceVendedorRoute
  '/planos/retorno': typeof PlanosRetornoRoute
  '/vendedor_/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor_/loja': typeof VendedorLojaRoute
  '/vendedor_/pedidos': typeof VendedorPedidosRoute
  '/vendedor_/publicacoes': typeof VendedorPublicacoesRoute
  '/api/marketplace/checkout': typeof ApiMarketplaceCheckoutRoute
  '/api/marketplace/order': typeof ApiMarketplaceOrderRoute
  '/api/marketplace/seller-onboarding': typeof ApiMarketplaceSellerOnboardingRoute
  '/marketplace_/item/$listingId': typeof MarketplaceItemListingIdRoute
  '/marketplace_/vendedor_/$sellerId': typeof MarketplaceVendedorSellerIdRoute
  '/api/public/marketplace/webhook': typeof ApiPublicMarketplaceWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/compras'
    | '/conta'
    | '/contato'
    | '/dashboard'
    | '/direitos-autorais'
    | '/editora'
    | '/estante-fisica'
    | '/mapa-literario'
    | '/marketplace'
    | '/meu-perfil'
    | '/planos'
    | '/privacidade'
    | '/reembolso'
    | '/social'
    | '/studio'
    | '/termos'
    | '/termos-vendedor'
    | '/vendedor'
    | '/admin/anuncios'
    | '/admin/assinaturas'
    | '/admin/contratos'
    | '/admin/dashboard'
    | '/admin/denuncias'
    | '/admin/doacoes'
    | '/admin/financeiro'
    | '/admin/marketplace'
    | '/admin/moderacao'
    | '/admin/pedidos'
    | '/admin/reembolsos'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/api/admin-mangas'
    | '/api/admin-users'
    | '/api/desktop-download'
    | '/api/drive-folder-sync'
    | '/api/r2-delete'
    | '/api/r2-upload'
    | '/api/reader-pages'
    | '/editora/catalogo'
    | '/editora/configuracoes'
    | '/editora/contratos'
    | '/editora/financeiro'
    | '/editora/relatorios'
    | '/ler/$volumeId'
    | '/manga/$slug'
    | '/marketplace/vendedor'
    | '/planos/retorno'
    | '/vendedor/financeiro'
    | '/vendedor/loja'
    | '/vendedor/pedidos'
    | '/vendedor/publicacoes'
    | '/api/marketplace/checkout'
    | '/api/marketplace/order'
    | '/api/marketplace/seller-onboarding'
    | '/marketplace/item/$listingId'
    | '/marketplace/vendedor/$sellerId'
    | '/api/public/marketplace/webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/compras'
    | '/conta'
    | '/contato'
    | '/dashboard'
    | '/direitos-autorais'
    | '/editora'
    | '/estante-fisica'
    | '/mapa-literario'
    | '/marketplace'
    | '/meu-perfil'
    | '/planos'
    | '/privacidade'
    | '/reembolso'
    | '/social'
    | '/studio'
    | '/termos'
    | '/termos-vendedor'
    | '/vendedor'
    | '/admin/anuncios'
    | '/admin/assinaturas'
    | '/admin/contratos'
    | '/admin/dashboard'
    | '/admin/denuncias'
    | '/admin/doacoes'
    | '/admin/financeiro'
    | '/admin/marketplace'
    | '/admin/moderacao'
    | '/admin/pedidos'
    | '/admin/reembolsos'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/api/admin-mangas'
    | '/api/admin-users'
    | '/api/desktop-download'
    | '/api/drive-folder-sync'
    | '/api/r2-delete'
    | '/api/r2-upload'
    | '/api/reader-pages'
    | '/editora/catalogo'
    | '/editora/configuracoes'
    | '/editora/contratos'
    | '/editora/financeiro'
    | '/editora/relatorios'
    | '/ler/$volumeId'
    | '/manga/$slug'
    | '/marketplace/vendedor'
    | '/planos/retorno'
    | '/vendedor/financeiro'
    | '/vendedor/loja'
    | '/vendedor/pedidos'
    | '/vendedor/publicacoes'
    | '/api/marketplace/checkout'
    | '/api/marketplace/order'
    | '/api/marketplace/seller-onboarding'
    | '/marketplace/item/$listingId'
    | '/marketplace/vendedor/$sellerId'
    | '/api/public/marketplace/webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/compras'
    | '/conta'
    | '/contato'
    | '/dashboard'
    | '/direitos-autorais'
    | '/editora'
    | '/estante-fisica'
    | '/mapa-literario'
    | '/marketplace'
    | '/meu-perfil'
    | '/planos'
    | '/privacidade'
    | '/reembolso'
    | '/social'
    | '/studio'
    | '/termos'
    | '/termos-vendedor'
    | '/vendedor'
    | '/admin_/anuncios'
    | '/admin_/assinaturas'
    | '/admin_/contratos'
    | '/admin_/dashboard'
    | '/admin_/denuncias'
    | '/admin_/doacoes'
    | '/admin_/financeiro'
    | '/admin_/marketplace'
    | '/admin_/moderacao'
    | '/admin_/pedidos'
    | '/admin_/reembolsos'
    | '/admin_/suporte'
    | '/admin_/usuarios'
    | '/api/admin-mangas'
    | '/api/admin-users'
    | '/api/desktop-download'
    | '/api/drive-folder-sync'
    | '/api/r2-delete'
    | '/api/r2-upload'
    | '/api/reader-pages'
    | '/editora_/catalogo'
    | '/editora_/configuracoes'
    | '/editora_/contratos'
    | '/editora_/financeiro'
    | '/editora_/relatorios'
    | '/ler/$volumeId'
    | '/manga/$slug'
    | '/marketplace_/vendedor'
    | '/planos/retorno'
    | '/vendedor_/financeiro'
    | '/vendedor_/loja'
    | '/vendedor_/pedidos'
    | '/vendedor_/publicacoes'
    | '/api/marketplace/checkout'
    | '/api/marketplace/order'
    | '/api/marketplace/seller-onboarding'
    | '/marketplace_/item/$listingId'
    | '/marketplace_/vendedor_/$sellerId'
    | '/api/public/marketplace/webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ComprasRoute: typeof ComprasRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  DireitosAutoraisRoute: typeof DireitosAutoraisRoute
  EditoraRoute: typeof EditoraRoute
  EstanteFisicaRoute: typeof EstanteFisicaRoute
  MapaLiterarioRoute: typeof MapaLiterarioRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MeuPerfilRoute: typeof MeuPerfilRoute
  PlanosRoute: typeof PlanosRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  SocialRoute: typeof SocialRoute
  StudioRoute: typeof StudioRoute
  TermosRoute: typeof TermosRoute
  TermosVendedorRoute: typeof TermosVendedorRoute
  VendedorRoute: typeof VendedorRoute
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminContratosRoute: typeof AdminContratosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminDoacoesRoute: typeof AdminDoacoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminModeracaoRoute: typeof AdminModeracaoRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminReembolsosRoute: typeof AdminReembolsosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ApiAdminMangasRoute: typeof ApiAdminMangasRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiDesktopDownloadRoute: typeof ApiDesktopDownloadRoute
  ApiDriveFolderSyncRoute: typeof ApiDriveFolderSyncRoute
  ApiR2DeleteRoute: typeof ApiR2DeleteRoute
  ApiR2UploadRoute: typeof ApiR2UploadRoute
  ApiReaderPagesRoute: typeof ApiReaderPagesRoute
  EditoraCatalogoRoute: typeof EditoraCatalogoRoute
  EditoraConfiguracoesRoute: typeof EditoraConfiguracoesRoute
  EditoraContratosRoute: typeof EditoraContratosRoute
  EditoraFinanceiroRoute: typeof EditoraFinanceiroRoute
  EditoraRelatoriosRoute: typeof EditoraRelatoriosRoute
  LerVolumeIdRoute: typeof LerVolumeIdRoute
  MangaSlugRoute: typeof MangaSlugRoute
  MarketplaceVendedorRoute: typeof MarketplaceVendedorRoute
  VendedorFinanceiroRoute: typeof VendedorFinanceiroRoute
  VendedorLojaRoute: typeof VendedorLojaRoute
  VendedorPedidosRoute: typeof VendedorPedidosRoute
  VendedorPublicacoesRoute: typeof VendedorPublicacoesRoute
  ApiMarketplaceCheckoutRoute: typeof ApiMarketplaceCheckoutRoute
  ApiMarketplaceOrderRoute: typeof ApiMarketplaceOrderRoute
  ApiMarketplaceSellerOnboardingRoute: typeof ApiMarketplaceSellerOnboardingRoute
  MarketplaceItemListingIdRoute: typeof MarketplaceItemListingIdRoute
  MarketplaceVendedorSellerIdRoute: typeof MarketplaceVendedorSellerIdRoute
  ApiPublicMarketplaceWebhookRoute: typeof ApiPublicMarketplaceWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direitos-autorais': {
      id: '/direitos-autorais'
      path: '/direitos-autorais'
      fullPath: '/direitos-autorais'
      preLoaderRoute: typeof DireitosAutoraisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editora': {
      id: '/editora'
      path: '/editora'
      fullPath: '/editora'
      preLoaderRoute: typeof EditoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estante-fisica': {
      id: '/estante-fisica'
      path: '/estante-fisica'
      fullPath: '/estante-fisica'
      preLoaderRoute: typeof EstanteFisicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-literario': {
      id: '/mapa-literario'
      path: '/mapa-literario'
      fullPath: '/mapa-literario'
      preLoaderRoute: typeof MapaLiterarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-perfil': {
      id: '/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof MeuPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-vendedor': {
      id: '/termos-vendedor'
      path: '/termos-vendedor'
      fullPath: '/termos-vendedor'
      preLoaderRoute: typeof TermosVendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/anuncios': {
      id: '/admin_/anuncios'
      path: '/admin/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/assinaturas': {
      id: '/admin_/assinaturas'
      path: '/admin/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/contratos': {
      id: '/admin_/contratos'
      path: '/admin/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AdminContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/denuncias': {
      id: '/admin_/denuncias'
      path: '/admin/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/doacoes': {
      id: '/admin_/doacoes'
      path: '/admin/doacoes'
      fullPath: '/admin/doacoes'
      preLoaderRoute: typeof AdminDoacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/financeiro': {
      id: '/admin_/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/marketplace': {
      id: '/admin_/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/moderacao': {
      id: '/admin_/moderacao'
      path: '/admin/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AdminModeracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/pedidos': {
      id: '/admin_/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reembolsos': {
      id: '/admin_/reembolsos'
      path: '/admin/reembolsos'
      fullPath: '/admin/reembolsos'
      preLoaderRoute: typeof AdminReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/suporte': {
      id: '/admin_/suporte'
      path: '/admin/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/usuarios': {
      id: '/admin_/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-mangas': {
      id: '/api/admin-mangas'
      path: '/api/admin-mangas'
      fullPath: '/api/admin-mangas'
      preLoaderRoute: typeof ApiAdminMangasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-users': {
      id: '/api/admin-users'
      path: '/api/admin-users'
      fullPath: '/api/admin-users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop-download': {
      id: '/api/desktop-download'
      path: '/api/desktop-download'
      fullPath: '/api/desktop-download'
      preLoaderRoute: typeof ApiDesktopDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-folder-sync': {
      id: '/api/drive-folder-sync'
      path: '/api/drive-folder-sync'
      fullPath: '/api/drive-folder-sync'
      preLoaderRoute: typeof ApiDriveFolderSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-delete': {
      id: '/api/r2-delete'
      path: '/api/r2-delete'
      fullPath: '/api/r2-delete'
      preLoaderRoute: typeof ApiR2DeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-upload': {
      id: '/api/r2-upload'
      path: '/api/r2-upload'
      fullPath: '/api/r2-upload'
      preLoaderRoute: typeof ApiR2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reader-pages': {
      id: '/api/reader-pages'
      path: '/api/reader-pages'
      fullPath: '/api/reader-pages'
      preLoaderRoute: typeof ApiReaderPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editora_/catalogo': {
      id: '/editora_/catalogo'
      path: '/editora/catalogo'
      fullPath: '/editora/catalogo'
      preLoaderRoute: typeof EditoraCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editora_/configuracoes': {
      id: '/editora_/configuracoes'
      path: '/editora/configuracoes'
      fullPath: '/editora/configuracoes'
      preLoaderRoute: typeof EditoraConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editora_/contratos': {
      id: '/editora_/contratos'
      path: '/editora/contratos'
      fullPath: '/editora/contratos'
      preLoaderRoute: typeof EditoraContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editora_/financeiro': {
      id: '/editora_/financeiro'
      path: '/editora/financeiro'
      fullPath: '/editora/financeiro'
      preLoaderRoute: typeof EditoraFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editora_/relatorios': {
      id: '/editora_/relatorios'
      path: '/editora/relatorios'
      fullPath: '/editora/relatorios'
      preLoaderRoute: typeof EditoraRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ler/$volumeId': {
      id: '/ler/$volumeId'
      path: '/ler/$volumeId'
      fullPath: '/ler/$volumeId'
      preLoaderRoute: typeof LerVolumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$slug': {
      id: '/manga/$slug'
      path: '/manga/$slug'
      fullPath: '/manga/$slug'
      preLoaderRoute: typeof MangaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/vendedor': {
      id: '/marketplace_/vendedor'
      path: '/marketplace/vendedor'
      fullPath: '/marketplace/vendedor'
      preLoaderRoute: typeof MarketplaceVendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/retorno': {
      id: '/planos/retorno'
      path: '/retorno'
      fullPath: '/planos/retorno'
      preLoaderRoute: typeof PlanosRetornoRouteImport
      parentRoute: typeof PlanosRoute
    }
    '/vendedor_/financeiro': {
      id: '/vendedor_/financeiro'
      path: '/vendedor/financeiro'
      fullPath: '/vendedor/financeiro'
      preLoaderRoute: typeof VendedorFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor_/loja': {
      id: '/vendedor_/loja'
      path: '/vendedor/loja'
      fullPath: '/vendedor/loja'
      preLoaderRoute: typeof VendedorLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor_/pedidos': {
      id: '/vendedor_/pedidos'
      path: '/vendedor/pedidos'
      fullPath: '/vendedor/pedidos'
      preLoaderRoute: typeof VendedorPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor_/publicacoes': {
      id: '/vendedor_/publicacoes'
      path: '/vendedor/publicacoes'
      fullPath: '/vendedor/publicacoes'
      preLoaderRoute: typeof VendedorPublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/checkout': {
      id: '/api/marketplace/checkout'
      path: '/api/marketplace/checkout'
      fullPath: '/api/marketplace/checkout'
      preLoaderRoute: typeof ApiMarketplaceCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/order': {
      id: '/api/marketplace/order'
      path: '/api/marketplace/order'
      fullPath: '/api/marketplace/order'
      preLoaderRoute: typeof ApiMarketplaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/seller-onboarding': {
      id: '/api/marketplace/seller-onboarding'
      path: '/api/marketplace/seller-onboarding'
      fullPath: '/api/marketplace/seller-onboarding'
      preLoaderRoute: typeof ApiMarketplaceSellerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/item/$listingId': {
      id: '/marketplace_/item/$listingId'
      path: '/marketplace/item/$listingId'
      fullPath: '/marketplace/item/$listingId'
      preLoaderRoute: typeof MarketplaceItemListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/vendedor_/$sellerId': {
      id: '/marketplace_/vendedor_/$sellerId'
      path: '/marketplace/vendedor/$sellerId'
      fullPath: '/marketplace/vendedor/$sellerId'
      preLoaderRoute: typeof MarketplaceVendedorSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketplace/webhook': {
      id: '/api/public/marketplace/webhook'
      path: '/api/public/marketplace/webhook'
      fullPath: '/api/public/marketplace/webhook'
      preLoaderRoute: typeof ApiPublicMarketplaceWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlanosRouteChildren {
  PlanosRetornoRoute: typeof PlanosRetornoRoute
}

const PlanosRouteChildren: PlanosRouteChildren = {
  PlanosRetornoRoute: PlanosRetornoRoute,
}

const PlanosRouteWithChildren =
  PlanosRoute._addFileChildren(PlanosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  ComprasRoute: ComprasRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  DireitosAutoraisRoute: DireitosAutoraisRoute,
  EditoraRoute: EditoraRoute,
  EstanteFisicaRoute: EstanteFisicaRoute,
  MapaLiterarioRoute: MapaLiterarioRoute,
  MarketplaceRoute: MarketplaceRoute,
  MeuPerfilRoute: MeuPerfilRoute,
  PlanosRoute: PlanosRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  SocialRoute: SocialRoute,
  StudioRoute: StudioRoute,
  TermosRoute: TermosRoute,
  TermosVendedorRoute: TermosVendedorRoute,
  VendedorRoute: VendedorRoute,
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminContratosRoute: AdminContratosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminDoacoesRoute: AdminDoacoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminModeracaoRoute: AdminModeracaoRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminReembolsosRoute: AdminReembolsosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ApiAdminMangasRoute: ApiAdminMangasRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiDesktopDownloadRoute: ApiDesktopDownloadRoute,
  ApiDriveFolderSyncRoute: ApiDriveFolderSyncRoute,
  ApiR2DeleteRoute: ApiR2DeleteRoute,
  ApiR2UploadRoute: ApiR2UploadRoute,
  ApiReaderPagesRoute: ApiReaderPagesRoute,
  EditoraCatalogoRoute: EditoraCatalogoRoute,
  EditoraConfiguracoesRoute: EditoraConfiguracoesRoute,
  EditoraContratosRoute: EditoraContratosRoute,
  EditoraFinanceiroRoute: EditoraFinanceiroRoute,
  EditoraRelatoriosRoute: EditoraRelatoriosRoute,
  LerVolumeIdRoute: LerVolumeIdRoute,
  MangaSlugRoute: MangaSlugRoute,
  MarketplaceVendedorRoute: MarketplaceVendedorRoute,
  VendedorFinanceiroRoute: VendedorFinanceiroRoute,
  VendedorLojaRoute: VendedorLojaRoute,
  VendedorPedidosRoute: VendedorPedidosRoute,
  VendedorPublicacoesRoute: VendedorPublicacoesRoute,
  ApiMarketplaceCheckoutRoute: ApiMarketplaceCheckoutRoute,
  ApiMarketplaceOrderRoute: ApiMarketplaceOrderRoute,
  ApiMarketplaceSellerOnboardingRoute: ApiMarketplaceSellerOnboardingRoute,
  MarketplaceItemListingIdRoute: MarketplaceItemListingIdRoute,
  MarketplaceVendedorSellerIdRoute: MarketplaceVendedorSellerIdRoute,
  ApiPublicMarketplaceWebhookRoute: ApiPublicMarketplaceWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
